services:
  app:
    build: .
    ports: ["8501:8501", "8000:8000"]
    volumes: ["./:/wms"]
    env_file: .env
    command: >
      sh -c "streamlit run src/streamlit_app.py --server.address=0.0.0.0 & uvicorn src.api:app --host 0.0.0.0 --port 8000"
  baserow:
    image: baserow/baserow:1.25.0
    env_file: .env
    ports: ["8080:80"]
